import helmet from 'helmet';
import type { Response } from 'express';

// Security headers middleware using Helmet configuring headers to protect against common vulnerabilities
export const securityHeaders = helmet({
  // HSTS: force HTTPS protecting against downgrade attacks and cookie hijacking
  strictTransportSecurity: {
    maxAge: 31536000, // 1 year
    includeSubDomains: true,
    preload: true, // inclusion in the HSTS preload list of browsers
  },

  // Content Security Policy with per-request nonce for inline scripts/styles
  // The nonce is generated by generateCspNonce middleware and stored in res.locals.cspNonce
  // Protects against XSS attacks and code injection
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", (req, res) => `'nonce-${(res as Response).locals.cspNonce}'`], // nonce for inline (no unsafe-inline needed)
      styleSrc: ["'self'", (req, res) => `'nonce-${(res as Response).locals.cspNonce}'`, "'unsafe-inline'"], // none for inline + unsafe-inline as fallback for older browsers
      imgSrc: ["'self'", 'data:'],
      fontSrc: ["'self'", 'data:'],
      connectSrc: ["'self'"],
      frameSrc: ["'none'"],
      frameAncestors: ["'none'"],
      objectSrc: ["'none'"],
      baseUri: ["'self'"],
      formAction: ["'self'", 'https://*.zendesk.com'],
    },
  },

  // X-Frame-Options: prevents the page from being loaded in an iframe (clickjacking attacks)
  frameguard: { action: 'deny' },

  // Referrer-Policy: controls how much referrer information is included with requests
  // strict-origin-when-cross-origin: sends full referrer for same-origin, only origin for cross-origin HTTPS
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },

  // X-DNS-Prefetch-Control: disables DNS prefetching
  // Improves privacy by preventing browsers from performing proactive DNS lookups
  dnsPrefetchControl: { allow: false },

  // X-Download-Options: prevents IE from executing downloads in the site's context
  ieNoOpen: true,

  // Disabled for compatibility with Zendesk redirects and auto-submit form
  crossOriginEmbedderPolicy: false,
  crossOriginOpenerPolicy: false,
  crossOriginResourcePolicy: false,
});
